# Netlify Functions 설정
[functions]
  directory = "api" # 서버리스 함수가 있는 폴더 이름 (weather.js, forecast.js가 있는 폴더)
  
# 경로 재작성 (Redirects) 설정
# /api/* 경로로 들어오는 모든 요청을 /netlify/functions/ 경로로 다시 작성합니다.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 # 상태 코드를 200으로 설정하여 클라이언트가 리다이렉트되었음을 모르게 합니다 (Proxy 역할)